#!/usr/bin/env python

import argparse
import re
import sys
import subprocess
import webbrowser


def fetch_remote(path):
    remote_parser = re.compile(r"^(?P<name>\w+)\s(?P<url>.+)\s(\(fetch\)|\(push\))")

    try:
        output = subprocess.check_output(["git", "-C", path, "remote", "-v"]).decode("utf-8")
    except subprocess.CalledProcessError:
        sys.exit(0)

    lines = output.split("\n")
    lines = [line for line in lines if line]

    remotes = []
    for line in lines:
        parsed_line = remote_parser.match(line)
        if parsed_line:
            remotes.append((parsed_line.group("name"), parsed_line.group("url")))

    remotes = set(remotes)

    return {remote: url for remote, url in remotes}


def get_branch():
    try:
        return subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).decode("utf-8").strip()
    except subprocess.CalledProcessError:
        sys.exit(0)



def get_remote(args):
    remotes = fetch_remote(args["path"])

    if remotes.get(args["remote"]):
        return remotes[args["remote"]]
    elif remotes.get("origin"):
        return remotes["origin"]
    elif len(remotes.keys()) <= 1:
        for value in remotes.values():
            return value
            break
    else:
        print("No remotes found")
        sys.exit(0)


def format_remote(remote):
    match = None

    if remote is None:
        print("Invalid remote")
        sys.exit(0)
    elif remote.startswith("https://"): # avoid having to potentially use both regexs
        match = re.match(r"^https://(?P<domain>\w+.\w+)/(?P<username>.+)/(?P<repository>.+).git$", remote)
    else:
        match = re.match(r"^git@(?P<domain>\w+.\w+):(?P<username>.+)/(?P<repository>.+).git$", remote)

    if not match:
        print("Could not parse remote url")
        sys.exit(0)

    return "http://{domain}/{username}/{repository}".format(**match.groupdict())


def parse_args():
    parser = argparse.ArgumentParser(description="A command line utility for opening a repositories remote homepage.")
    parser.add_argument("-r", "--remote", required=False, help="remote to open. default: origin")
    parser.add_argument("path", nargs="?", default=".", help="path to local repository, defaults to '.'")
    args = parser.parse_args()

    return vars(args)

def main():
    args = parse_args()

    remote = get_remote(args)

    url = format_remote(remote)

    branch = get_branch()

    webbrowser.open("{url}/pull/{branch}".format(url=url, branch=branch))


main()
